MODEL:
  META_ARCHITECTURE: "TensorMask"
  MASK_ON: True
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 50
  ANCHOR_GENERATOR:
    SIZES: [[16, 16], [32, 32], [64, 64], [128, 128], [256, 256], [512, 512]]
    ASPECT_RATIOS: [[1.0]]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    FUSE_TYPE: "avg"
  TENSOR_MASK:
    ALIGNED_ON: True
    BIPYRAMID_ON: True
    NUM_CLASSES: 1
    FOCAL_LOSS_GAMMA: 1 # Disable focal loss
    FOCAL_LOSS_ALPHA: 1

DATASETS:
  TRAIN: ("/local_storage/datasets/xview2/full_no_dense/train/",)
  TEST: ("/local_storage/datasets/xview2/full_no_dense/test/",)
OUTPUT_DIR_BASE: "/local_storage/users/pshi/detectron2"
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.0025
  MAX_ITER: 1200000
  WARMUP_ITERS: 10000
  CHECKPOINT_PERIOD: 20000
TEST:
  DETECTIONS_PER_IMAGE: 1000
