_BASE_: "base.yaml"
MODEL:
  MASK_ON: True
DATASETS:
  TRAIN: ("/storage/yonk/debug/train/",)
  TEST: ("/storage/yonk/debug/test/",)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 0
TEST:
  DETECTIONS_PER_IMAGE: 1000
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025
  MAX_ITER: 1000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
