_BASE_: "basic.yaml"
MODEL:
  RESNETS:
    DEPTH: 101
DATASETS:
  TRAIN: ("/storage/yonk/debug/train/",)
  TEST: ("/storage/yonk/debug/test/",)
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.0025
  MAX_ITER: 1000
INPUT:
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TRAIN: (1024,)
