_BASE_: "damage_base.yaml"
MODEL:
  LOSS_TYPE: 'ComboLoss'
  OUT_CHANNELS: 5
  IN_CHANNELS: 7
#  PRETRAINED:
#    ENABLED: False
#    NAME: 'debug' # Name of the pretrained model
#    CP_FILE: 'dice_2xdown.pkl' # Checkpoint file
#    ENCODER_ONLY: True # full, encoder
#    INCLUDE_INPUT_LAYER: False # If true, weights from input layer will be included too (only if they have the same dims

  BACKBONE:
    ENABLED: True
    TYPE: 'resnet50'
  COMPLEX_ARCHITECTURE:
    ENABLED: True
    TYPE: 'pspnet'

OUTPUT_BASE_DIR: ('logs/')
DATASETS:
  TRAIN: ("/storage/yonk/debug_new/train/",)
  TEST: ("/storage/yonk/debug_new/test/",)
  INFERENCE: ("/storage/yonk/debug_new/test/",)
  LOCALIZATION_MASK:
    ENABLED: True
    TRAIN_USE_GTS_MASK: False # If false, we will use predicted localization to train
  INCLUDE_PRE_DISASTER: True
TRAINER:
  LR: 0.001
  BATCH_SIZE: 8
DATALOADER:
  NUM_WORKER: 0
AUGMENTATION:
  # Random cropping of the images
  CROP_TYPE: 'importance'
  CROP_SIZE: 512
  IMAGE_OVERSAMPLING_TYPE: 'simple'



