_BASE_: "damage_base.yaml"
MODEL:
  LOSS_TYPE: 'CrossEntropyLoss'
  OUT_CHANNELS: 5
  IN_CHANNELS: 4
OUTPUT_BASE_DIR: ('logs/')
DATASETS:
  TRAIN: ("/storage/yonk/debug_new/train/",)
  TEST: ("/storage/yonk/debug_new/test/",)
  INFERENCE: ("/storage/yonk/debug_new/test/",)
TRAINER:
  LR: 0.001
  BATCH_SIZE: 8
DATALOADER:
  NUM_WORKER: 0
AUGMENTATION:
  # Random cropping of the images
  CROP_TYPE: 'uniform'
  CROP_SIZE: 256

