_BASE_: "damage_base.yaml"
MODEL:
  LOSS_TYPE: 'SoftDiceMulticlassLossDebug'
  IN_CHANNELS: 7
  TOPOLOGY: [32, 64, 128, 256,]
DATASETS:
  LOCALIZATION_MASK:
    ENABLED: True
    TRAIN_USE_GTS_MASK: False # If false, we will use predicted localization to train
  INCLUDE_PRE_DISASTER: True
TRAINER:
  BATCH_SIZE: 12
DATALOADER:
  NUM_WORKER: 8
AUGMENTATION:
  # Random cropping of the images
  CROP_TYPE: 'uniform'
  CROP_SIZE: 512





