_BASE_: "damage_base.yaml"
MODEL:
  LOSS_TYPE: 'CrossEntropyLoss'
  IN_CHANNELS: 7
TRAINER:
  BATCH_SIZE: 16
DATALOADER:
  NUM_WORKER: 8
AUGMENTATION:
  # Random cropping of the images
  CROP_TYPE: 'uniform'
  CROP_SIZE: 256
  INCLUDE_PRE_DISASTER: True




