_BASE_: "damage_base.yaml"
MODEL:
  LOSS_TYPE: 'ComboLoss'
  OUT_CHANNELS: 4
  IN_CHANNELS: 7
  BACKGROUND:   # Include background class in the inference
    TYPE: 'no-damage' # 'new-class', 'no-damage', 'None'
    MASK_OUTPUT: True
    MASKED_GRADIENT: False
DATASETS:
  LOCALIZATION_MASK:
    ENABLED: True
    TRAIN_USE_GTS_MASK: False # If false, we will use predicted localization to train
  INCLUDE_PRE_DISASTER: True
TRAINER:
  BATCH_SIZE: 12
DATALOADER:
  NUM_WORKER: 8
AUGMENTATION:
  # Random cropping of the images
  CROP_TYPE: 'importance'
  CROP_SIZE: 512
  IMAGE_OVERSAMPLING_TYPE: 'simple'




