_BASE_: "damage_base.yaml"
MODEL:
  IN_CHANNELS: 6
  PRETRAINED:
    ENABLED: True
    NAME: 'frankenstein_oversample_3conv' # Name of the pretrained model
    CP_FILE: 'cp_170000.pkl' # Checkpoint file
    ENCODER_ONLY: False # full, encoder
    INCLUDE_INPUT_LAYER: False
DATASETS:
  LOCALIZATION_MASK:
    ENABLED: False
  INCLUDE_PRE_DISASTER: True
TRAINER:
  BATCH_SIZE: 16
DATALOADER:
  NUM_WORKER: 8
AUGMENTATION:
  # Random cropping of the images
  CROP_TYPE: 'uniform'
  CROP_SIZE: 256





