_BASE_: "base_realestate_stockholm.yaml"
THRESH: 0
MODEL:
  IN_CHANNELS: 8
DATALOADER:
  SENTINEL1:
    POLARIZATIONS: ['VV', 'VH']
    ORBITS: ['asc', 'desc']
    METRICS: ['singlescene']
  SENTINEL2:
    BANDS: ['Blue', 'Green', 'Red', 'NIR']
    INDICES: []
    METRICS: ['singlescene']