_BASE_: "base_realestate_stockholm_time_series.yaml"
THRESH: 0
MODEL:
  IN_CHANNELS: 20
DATALOADER:
  SENTINEL1:
    POLARIZATIONS: []
    ORBITS: []
    METRICS: []
  SENTINEL2:
    BANDS: ['Blue', 'Green', 'Red', 'NIR']
    INDICES: []
    METRICS: ['mean', 'median', 'iqr', 'min', 'max']