_BASE_: "base_realestate_stockholm.yaml"
THRESH: 0
MODEL:
  IN_CHANNELS: 10
DATALOADER:
  SENTINEL1:
    POLARIZATIONS: []
    ORBITS: []
    METRICS: []
  SENTINEL2:
    BANDS: ['Blue', 'Green', 'Red', 'RedEdge1', 'RedEdge2', 'RedEdge3', 'NIR', 'RedEdge4', 'SWIR1', 'SWIR2']
    INDICES: []
    METRICS: ['singlescene']