SEED: 42 # best seed so far 42
DEBUG: False
THRESH: 0.0 # Best threshold (only to be filled after running final model evaluation)
OUTPUT_BASE_DIR: ('/storage/shafner/run_logs/unet/')
SAVE_MODEL: True

MODEL:
  BINARY_CLASSIFICATION: True
  OUT_CHANNELS: 1
  IN_CHANNELS: 8
  LOSS_TYPE: 'FrankensteinLoss'
  POSITIVE_WEIGHT: 250
  NEGATIVE_WEIGHT: 1
  LEGACY: False # If True, use the fixed UNet for backwards compatibility
  TOPOLOGY: [64, 128, 256, 512,]
  BLOCK_TYPE: 'Double' # Double = Double conv, Triple = Triple conv, for greater receptive field
  SIMPLE_INTERPOLATION: False # True: Bilinear interpo, False: Deconv interpo
  USE_ATTENTION: False
  MULTISCALE_CONTEXT: # For U-Net bottleneck context module
    ENABLED: False
    TYPE: 'Simple' # [Simple, PyramidSum, ParallelSum]
    DILATION: []
  BACKBONE:
    ENABLED: False
    TYPE: 'resnet34'
    PRETRAINED_WEIGHTS: None

DATALOADER:
  NUM_WORKER: 8
  SHUFFLE: True
  LEGACY_MASK_RASTERIZATION: False
  LABEL: 'buildings'
  LABEL_THRESH: 0.0
  SENTINEL1_BANDS: ['VV', 'VH']
  SENTINEL2_BANDS: ['B2', 'B3', 'B4', 'B8', 'B11', 'B12']

DATASETS:
  PATH: '/storage/shafner/urban_extraction/urban_extraction_buildings/'
  TRAIN: ['dallas', 'miami', 'vancouver', 'toronto', 'newyork', 'kampala']
  TEST: ['losangeles', 'daressalaam']
  USE_CLAHE_VARI: False

TRAINER:
  LR: 8e-4
  BATCH_SIZE: 16
  EPOCHS: 200
  EDGE_LOSS_SCALE: 1

AUGMENTATION:
  RESIZE: False # target image size (before cropping)
  RESIZE_RATIO: 1.0
  CROP_TYPE: 'none'
  CROP_SIZE: 1024
  IMAGE_OVERSAMPLING_TYPE: 'none' # [none, simple]
  ENABLE_VARI: False # False NDVI for detecting vegetation
  RANDOM_FLIP: True
  RANDOM_ROTATE: True
  SENSOR_DROPOUT: False
  DROPOUT_PROBABILITY: 0.5