_BASE_: "base_realestate_stockholm.yaml"
THRESH: 0
MODEL:
  IN_CHANNELS: 2
DATALOADER:
  SENTINEL1:
    POLARIZATIONS: ['VV', 'VH']
    ORBITS: ['asc']
    METRICS: ['singlescene']
  SENTINEL2:
    BANDS: []
    INDICES: []
    METRICS: []