_BASE_: "base.yaml"
THRESH: 0.0
DEBUG: True

MODEL:
  IN_CHANNELS: 8
  BACKBONE:
    ENABLED: True
    TYPE: 'resnet34'
    PRETRAINED_WEIGHTS: 'imagenet'

DATALOADER:
  SENTINEL1_BANDS: ['VV', 'VH']
  SENTINEL2_BANDS: ['B4', 'B3', 'B2', 'B8', 'B11', 'B12']