_BASE_: "base.yaml"
THRESH: 0.0

MODEL:
  IN_CHANNELS: 8
  LOSS_TYPE: 'JaccardLikeLoss'

TRAINER:
  LR: 1e-4

DATALOADER:
  SENTINEL1_BANDS: ['VV', 'VH']
  SENTINEL2_BANDS: ['B2', 'B3', 'B4', 'B8', 'B11', 'B12']