_BASE_: "base.yaml"
THRESH: 0.0
SAVE_MODEL: False
DEBUG: False

MODEL:
  IN_CHANNELS: 8
  LOSS_TYPE: 'JaccardLikeLoss'

TRAINER:
  LR: 1e-4
  BATCH_SIZE: 32

DATALOADER:
  SENTINEL1_BANDS: ['VV', 'VH']
  SENTINEL2_BANDS: ['B2', 'B3', 'B4', 'B8', 'B11', 'B12']