_BASE_: "base_bp_stockholm.yaml"
THRESH: 0.0
MODEL:
  IN_CHANNELS: 8
DATALOADER:
  SENTINEL1:
    POLARIZATIONS: ['VV', 'VH']
    ORBITS: ['asc']
    METRICS: ['median', 'iqr']
  SENTINEL2:
    BANDS: ['Blue', 'Green', 'Red', 'NIR']
    INDICES: []
    METRICS: ['median']
  LABEL: 'bp'
  LABEL_THRESH: 0
TRAINER:
  LR: 1e-6
  EPOCHS: 1000
AUGMENTATION:
  RANDOM_FLIP_ROTATE: True