_BASE_: "base_realestate_stockholm_time_series.yaml"
THRESH: 0
MODEL:
  IN_CHANNELS: 30
DATALOADER:
  SENTINEL1:
    POLARIZATIONS: ['VV', 'VH']
    ORBITS: ['asc']
    METRICS: ['mean', 'median', 'iqr', 'min', 'max']
  SENTINEL2:
    BANDS: ['Blue', 'Green', 'Red', 'NIR']
    INDICES: []
    METRICS: ['mean', 'median', 'iqr', 'min', 'max']