_BASE_: "base_realestate_stockholm.yaml"
THRESH: 0
MODEL:
  IN_CHANNELS: 6
DATALOADER:
  SENTINEL1:
    POLARIZATIONS: []
    ORBITS: []
    METRICS: []
  SENTINEL2:
    BANDS: ['Blue', 'Green', 'Red', 'NIR', 'SWIR1', 'SWIR2']
    INDICES: []
    METRICS: ['singlescene']