_BASE_: "base.yaml"
THRESH: 0.0
DEBUG: True

MODEL:
  IN_CHANNELS: 3
  BACKBONE:
    ENABLED: True
    TYPE: 'resnet34'
    PRETRAINED_WEIGHTS: 'imagenet'

DATALOADER:
  SENTINEL1_BANDS: []
  SENTINEL2_BANDS: ['B4', 'B3', 'B2']