_BASE_: "base.yaml"
THRESH: 0.36
SEED: 42
MODEL:
  LOSS_TYPE: 'FrankensteinLoss'
  OUT_CHANNELS: 1
  IN_CHANNELS: 26
DATALOADER:
  LABEL: 'realestate'
  SENTINEL1:
    POLARIZATIONS: ['VV', 'VH']
    ORBITS: ['asc', 'desc']
    METRICS: ['mean', 'stdDev', 'min', 'max']
  SENTINEL2:
    BANDS: ['Blue', 'Green', 'Red', 'RedEdge1', 'RedEdge2', 'RedEdge3', 'NIR', 'RedEdge4', 'SWIR1', 'SWIR2']
    INDICES: []
    METRICS: ['median']
DATASETS:
  TRAIN: ("/storage/shafner/urban_extraction/urban_extraction_realestate_stockholm/",)
  TEST: ("/storage/shafner/urban_extraction/urban_extraction_realestate_stockholm/",)
  INFERENCE: ("/storage/yonk/debug_new/test/",)
  USE_CLAHE_VARI: False
OUTPUT_BASE_DIR: ('/storage/shafner/run_logs/unet/')
TRAINER:
  LR: 0.0001
  BATCH_SIZE: 16
  EPOCHS: 50
AUGMENTATION:
  IMAGE_OVERSAMPLING_TYPE: 'simple'