_BASE_: "s1_allbands.yaml"
DATASETS:
  TRAIN: ("/Midgard/Data/pshi/datasets/sentinel/preprocessed/urban_extraction_twocities/train/",)
  TEST: ("/Midgard/Data/pshi/datasets/sentinel/preprocessed/urban_extraction_twocities/test/",)
