_BASE_: "s1_allbands.yaml"
THRESH: 0.32
MODEL:
  IN_CHANNELS: 2
DATALOADER:
  S1_FEATURES: ['VV_asc_mean', 'VH_asc_mean']
DATASETS:
  TRAIN: ("/Midgard/Data/pshi/datasets/sentinel/preprocessed/urban_extraction_twocities/train/",)
  TEST: ("/Midgard/Data/pshi/datasets/sentinel/preprocessed/urban_extraction_twocities/test/",)
