_BASE_: "s1_allbands.yaml"
DATALOADER:
  S1_FEATURES: ['VV_desc_mean', 'VH_desc_mean']
DATASETS:
  TRAIN: ("/Midgard/Data/pshi/datasets/sentinel/preprocessed/urban_extraction_twocities/train/",)
  TEST: ("/Midgard/Data/pshi/datasets/sentinel/preprocessed/urban_extraction_twocities/test/",)
