_BASE_: "s1s2_allbands.yaml"
DATASETS:
  TRAIN: ("/Midgard/Data/pshi/datasets/sentinel/preprocessed/urban_extraction_morecities/train/",)
  TEST: ("/Midgard/Data/pshi/datasets/sentinel/preprocessed/urban_extraction_morecities/test/",)
