_BASE_: "base.yaml"
MODEL:
  LOSS_TYPE: 'FrankensteinLoss'
  OUT_CHANNELS: 1
  IN_CHANNELS: 10
DATASETS:
  TRAIN: ("/Midgard/Data/pshi/datasets/sentinel/preprocessed/two_cities/train/",)
  TEST: ("/Midgard/Data/pshi/datasets/sentinel/preprocessed/two_cities/test/",)
TRAINER:
  BATCH_SIZE: 8
DATALOADER:
  S1_FEATURES: []
  S2_FEATURES: ['Blue_median', 'Green_median', 'Red_median', 'RedEdge1_median','RedEdge2_median','RedEdge3_median', 'NIR_median','RedEdge4_median', 'SWIR1_median', 'SWIR2_median']
  LABEL: 'guf'
AUGMENTATION:
  # Random cropping of the images
  CROP_TYPE: 'importance'
  CROP_SIZE: 256
  IMAGE_OVERSAMPLING_TYPE: 'simple'
