_BASE_: "base.yaml"
MODEL:
  LOSS_TYPE: 'FrankensteinLoss'
  OUT_CHANNELS: 1
  IN_CHANNELS: 3
DATALOADER:
  S1_FEATURES: []
  S2_FEATURES: ['Green_median', 'Red_median', 'NIR_median']
  LABEL: 'guf'
AUGMENTATION:
  IMAGE_OVERSAMPLING_TYPE: 'simple'
