_BASE_: "base.yaml"
MODEL:
  POSITIVE_WEIGHT: 250
  LEGACY: True
OUTPUT_BASE_DIR: ('logs/')
DATASETS:
  TRAIN: ("/storage/yonk/debug/train/",)
  TEST: ("/storage/yonk/debug/test/",)
  INFERENCE: ("/storage/yonk/debug/test/",)
TRAINER:
  LR: 0.001
  BATCH_SIZE: 8
DATALOADER:
  NUM_WORKER: 0
AUGMENTATION:
  # Random cropping of the images
  CROP: True
  CROP_SIZE: 256