_BASE_: "base.yaml"
MODEL:
  POSITIVE_WEIGHT: 250
  LOSS_TYPE: 'CustomCELoss'
  OUT_CHANNELS: 1
OUTPUT_BASE_DIR: ('logs/')
DATASETS:
  TRAIN: ("/storage/yonk/debug/train/",)
  TEST: ("/storage/yonk/debug/train/",)
EVAL:
  WTF: "123"
DATALOADER:
  NUM_WORKER: 0