_BASE_: "base_v3.yaml"

TRESHOLDS:
  TRAIN: 0.0
  VALIDATION: 0.0

MODEL:
  IN_CHANNELS: 4

DATALOADER:
  MODE: 'sar'
  SENTINEL1_BANDS: ['VV_mean', 'VV_stdDev', 'VH_mean', 'VH_stdDev']

DATASETS:
  SITES:
    TRAINING: ['saltlakecity', 'phoenix', 'lasvegas', 'losangeles', 'albuquerque', 'elpaso', 'sandiego', 'santafe',
               'stgeorge', 'tucson']