SEED: 42 # best seed so far 42
DEBUG: False
THRESH: 0.0 # Best threshold (only to be filled after running final model evaluation)
OUTPUT_BASE_DIR: '/storage/shafner/urban_extraction/networks'
SAVE_CHECKPOINTS: [100, 150, 200]

MODEL:
  TYPE: 'unet'
  OUT_CHANNELS: 1
  IN_CHANNELS: 12
  LOSS_TYPE: 'FrankensteinLoss'
  POSITIVE_WEIGHT: 250
  NEGATIVE_WEIGHT: 1
  TOPOLOGY: [64, 128, 256, 512,]
  BACKBONE:
    ENABLED: False
    TYPE: 'resnet34'
    PRETRAINED_WEIGHTS: None

DATALOADER:
  NUM_WORKER: 16
  SHUFFLE: True
  LABEL: 'buildings'
  LABEL_THRESH: 0.0
  MODE: 'fusion'
  SENTINEL1_BANDS: ['VV', 'VH']
  SENTINEL2_BANDS: ['B2', 'B3', 'B4', 'B5', 'B6', 'B6', 'B8', 'B8A', 'B11', 'B12']
  ANCILLARY_INPUT: None

DATASETS:
  PATH: '/storage/shafner/urban_extraction/urban_extraction/'
  SITES:
    TRAINING: ['denver', 'saltlakecity', 'phoenix', 'lasvegas', 'toronto', 'columbus', 'winnipeg', 'dallas',
               'minneapolis', 'atlanta', 'miami', 'montreal', 'quebec', 'albuquerque', 'losangeles', 'kansascity',
               'charlston', 'seattle', 'daressalam']
    VALIDATION: ['houston', 'sanfrancisco', 'vancouver', 'newyork', 'calgary', 'kampala']
  TESTING: '/storage/shafner/urban_extraction/urban_extraction/sn7/'

TRAINER:
  LR: 1e-5
  BATCH_SIZE: 16
  EPOCHS: 101
  EARLY_STOPPING: False
  PATIENCE: 5



AUGMENTATION:
  IMAGE_OVERSAMPLING_TYPE: 'none' # [none, simple]
  RANDOM_FLIP: True
  RANDOM_ROTATE: True
  SENSOR_DROPOUT: False
  DROPOUT_PROBABILITY: 0.5