_BASE_: "base_v2.yaml"
DEBUG: False
THRESHOLDS:
  TRAIN: 0.44
  VALIDATION: 0.39

MODEL:
  TYPE: 'unet'
  IN_CHANNELS: 10

DATALOADER:
  MODE: 'optical'
  SENTINEL1_BANDS: []
  SENTINEL2_BANDS: ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B11', 'B12']