SEED: 7
DEBUG: False
OUTPUT_BASE_DIR: '/storage/shafner/urban_extraction/networks'
SAVE_CHECKPOINTS: [50, 75, 100]
TRESHOLDS:
  TRAIN: 0.0
  VALIDATION: 0.0

MODEL:
  TYPE: 'unet'
  OUT_CHANNELS: 1
  IN_CHANNELS: 12
  LOSS_TYPE: 'FrankensteinLoss'
  POSITIVE_WEIGHT: 250
  NEGATIVE_WEIGHT: 1
  TOPOLOGY: [64, 128, 256, 512,]
  BACKBONE:
    ENABLED: False
    TYPE: 'resnet34'
    PRETRAINED_WEIGHTS: None

DATALOADER:
  NUM_WORKER: 16
  SHUFFLE: True
  LABEL: 'buildings'
  LABEL_THRESH: 0.0
  MODE: 'fusion'
  SENTINEL1_BANDS: ['VV_mean', 'VV_stdDev', 'VH_mean', 'VH_stdDev']
  SENTINEL2_BANDS: ['B2', 'B3', 'B4', 'B5', 'B6', 'B6', 'B8', 'B8A', 'B11', 'B12']
  AUXILIARY_INPUTS: []

DATASETS:
  PATH: '/storage/shafner/urban_extraction/urban_extraction_dataset/'
  SITES:
    TRAINING: ['denver', 'saltlakecity', 'phoenix', 'lasvegas', 'toronto', 'columbus', 'winnipeg', 'dallas',
               'minneapolis', 'atlanta', 'miami', 'montreal', 'quebec', 'albuquerque', 'losangeles', 'kansascity',
               'charlston', 'seattle', 'daressalam']
    VALIDATION: ['houston', 'sanfrancisco', 'vancouver', 'newyork', 'calgary', 'kampala']
  TESTING: '/storage/shafner/urban_extraction/urban_extraction_dataset/sn7/'

TRAINER:
  LR: 1e-5
  BATCH_SIZE: 16
  EPOCHS: 101

AUGMENTATION:
  IMAGE_OVERSAMPLING_TYPE: 'none' # [none, simple]
  RANDOM_FLIP: True
  RANDOM_ROTATE: True
  COLOR_SHIFT: False