_BASE_: "base_extended.yaml"
DEBUG: True
LOG_FREQ: 500
SAVE_CHECKPOINTS: [5, 10, 15, 20]
INFERENCE:
  CHECKPOINT: 0
  THRESHOLDS:
    TRAIN: 0.00
    VALIDATION: 0.00

MODEL:
  TYPE: 'dualstreamunet'
  IN_CHANNELS: 12

TRAINER:
  EPOCHS: 20

DATALOADER:
  MODE: 'fusion'

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.1
  WEIGHT_DECAY: 0.998
  APPLY_THRESHOLD: False
  CONSISTENCY_LOSS_TYPE: 'BCEWithLogitsLoss'

AUGMENTATION:
  COLOR_SHIFT: False
  GAMMA_CORRECTION: True