_BASE_: "base.yaml"
MODEL:
  LOSS_TYPE: 'ComboLoss'
  OUT_CHANNELS: 1
OUTPUT_BASE_DIR: ('logs/')
DATASETS:
  TRAIN: ("/storage/yonk/debug/train/",)
  TEST: ("/storage/yonk/debug/test/",)
  INFERENCE: ("/storage/yonk/debug/test/",)
TRAINER:
  LR: 0.001
  BATCH_SIZE: 8
DATALOADER:
  NUM_WORKER: 0
AUGMENTATION:
  # Random cropping of the images
  CROP_TYPE: 'importance'
  CROP_SIZE: 256
  IMAGE_OVERSAMPLING_TYPE: 'simple'
