SEED: 42 # best seed so far 42
DEBUG: True
THRESH: 0.0 # Best threshold (only to be filled after running final model evaluation)
OUTPUT_BASE_DIR: '/storage/shafner/urban_extraction/networks'
SAVE_MODEL: True

MODEL:
  TYPE: 'unet'
  OUT_CHANNELS: 1
  IN_CHANNELS: 10
  LOSS_TYPE: 'FrankensteinLoss'
  POSITIVE_WEIGHT: 250
  NEGATIVE_WEIGHT: 1
  TOPOLOGY: [64, 128, 256, 512,]
  BACKBONE:
    ENABLED: False
    TYPE: 'resnet34'
    PRETRAINED_WEIGHTS: None

DATALOADER:
  NUM_WORKER: 8
  SHUFFLE: True
  LABEL: 'buildings'
  LABEL_THRESH: 0.0
  MODEL: 'optical'
  SENTINEL1_BANDS: []
  SENTINEL2_BANDS: ['B2', 'B3', 'B4', 'B5', 'B6', 'B6', 'B8', 'B8A', 'B11', 'B12']

DATASETS:
  PATH: '/storage/shafner/urban_extraction/urban_extraction/'
  TRAIN: ['calgary']
  TEST: ['kampala']

TRAINER:
  LR: 1e-5
  BATCH_SIZE: 16
  EPOCHS: 1

AUGMENTATION:
  IMAGE_OVERSAMPLING_TYPE: 'none' # [none, simple]
  RANDOM_FLIP: True
  RANDOM_ROTATE: True
  SENSOR_DROPOUT: False
  DROPOUT_PROBABILITY: 0.5