_BASE_: "base.yaml"
DEBUG: False
SAVE_CHECKPOINTS: [10, 15, 20, 25, 30]
INFERENCE:
  CHECKPOINT: 15
  THRESHOLDS:
    TRAIN: 0.00
    VALIDATION: 0.00

TRAINER:
  EPOCHS: 30
  BATCH_SIZE: 8

MODEL:
  TYPE: 'dualstreamunet'
  IN_CHANNELS: 12

DATALOADER:
  MODE: 'fusion'

AUGMENTATION:
  COLOR_SHIFT: False
  GAMMA_CORRECTION: True
