_BASE_: "fusion.yaml"
DEBUG: False

THRESHOLDS:
  TRAIN: 0.25
  VALIDATION: 0.16

MODEL:
  TOPOLOGY: [64, 128,]

DATALOADER:
  FUSION_DROPOUT: True

AUGMENTATION:
  COLOR_SHIFT: False
  GAMMA_CORRECTION: True