_BASE_: "base.yaml"
DEBUG: False
INFERENCE:
  CHECKPOINT: 100
  THRESHOLDS:
    TRAIN: 0.0
    VALIDATION: 0.0

TRAINER:
  LR: 1e-4
  BATCH_SIZE: 16

MODEL:
  TYPE: 'unet'
  IN_CHANNELS: 12

DATALOADER:
  MODE: 'fusion'

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.1
  APPLY_THRESHOLD: False
  CONSISTENCY_LOSS_TYPE: 'MeanSquareErrorLoss'