_BASE_: "base.yaml"
THRESH: 0.0

MODEL:
  TYPE: 'dualstreamunet'
  OUT_CHANNELS: 1
  IN_CHANNELS: 8
  LOSS_TYPE: 'FrankensteinLoss'
  TOPOLOGY: [64, 128, 256, 512,]

DATALOADER:
  SENTINEL1_BANDS: ['VV', 'VH']
  SENTINEL2_BANDS: ['B2', 'B3', 'B4', 'B8', 'B11', 'B12']

TRAINER:
  BATCH_SIZE: 8
