_BASE_: "base_v3.yaml"
DEBUG: False
THRESHOLDS:
  TRAIN: 0.0
  VALIDATION: 0.0

MODEL:
  TYPE: 'unet'
  IN_CHANNELS: 14

DATALOADER:
  MODE: 'fusion'
  SENTINEL1_BANDS: ['VV_mean', 'VV_stdDev', 'VH_mean', 'VH_stdDev']
  SENTINEL2_BANDS: ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B11', 'B12']