_BASE_: "base_new.yaml"
DEBUG: False
LOG_FREQ: 1000
SAVE_CHECKPOINTS: [5, 10, 15, 20]
INFERENCE:
  CHECKPOINT: 20
  THRESHOLDS:
    TRAIN: 0.00
    VALIDATION: 0.00

MODEL:
  TYPE: 'dualstreamunet'
  IN_CHANNELS: 12
  LOSS_TYPE: 'BCEWithLogitsLoss'

TRAINER:
  EPOCHS: 20

DATALOADER:
  MODE: 'fusion'
  INCLUDE_UNLABELED: True

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.1
  WEIGHT_DECAY: 0.998
  APPLY_THRESHOLD: False
  CONSISTENCY_LOSS_TYPE: 'BCEWithLogitsLoss'