_BASE_: "base.yaml"
DEBUG: False
LOG_FREQ: 500
INFERENCE:
  CHECKPOINT: 20
  THRESHOLDS:
    TRAIN: 0.00
    VALIDATION: 0.00

MODEL:
  TYPE: 'dualstreamunet'
  IN_CHANNELS: 12

DATALOADER:
  MODE: 'fusion'
  INCLUDE_UNLABELED: True

CONSISTENCY_TRAINER:
  CONSISTENCY_LOSS_TYPE: 'MeanSquareErrorLoss'