_BASE_: "base.yaml"
DEBUG: False
INFERENCE:
  CHECKPOINT: 50
  THRESHOLDS:
    TRAIN: 0.0
    VALIDATION: 0.0

MODEL:
  TYPE: 'unet'
  IN_CHANNELS: 12

DATALOADER:
  MODE: 'fusion'

TRAINER:
  BATCH_SIZE: 8
  LR: 1e-4