_BASE_: "base.yaml"
DEBUG: False
INFERENCE:
  CHECKPOINT: 10
  THRESHOLDS:
    TRAIN: 0.60
    VALIDATION: 0.43

MODEL:
  TYPE: 'dualstreamunet'
  IN_CHANNELS: 12

TRAINER:
  BATCH_SIZE: 8

DATALOADER:
  MODE: 'fusion'

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.1
  WEIGHT_DECAY: 0.998
  APPLY_THRESHOLD: False
  CONSISTENCY_LOSS_TYPE: 'JaccardLikeLoss'

AUGMENTATION:
  COLOR_SHIFT: False
  GAMMA_CORRECTION: True