_BASE_: "base_version4.yaml"
DEBUG: False
THRESHOLDS:
  TRAIN: 0.0
  VALIDATION: 0.0

DATASETS:
  SITES:
    TRAINING: ['denver', 'saltlakecity', 'phoenix', 'lasvegas', 'toronto', 'columbus', 'winnipeg', 'dallas',
               'minneapolis', 'miami', 'montreal', 'quebec', 'albuquerque', 'losangeles', 'kansascity',
               'charlston', 'seattle', 'daressalam', 'elpaso', 'sandiego', 'santafe', 'stgeorge', 'tucson']
    VALIDATION: ['sanfrancisco', 'atlanta', 'vancouver', 'calgary', 'kampala']