_BASE_: "base.yaml"
DEBUG: True
INFERENCE:
  CHECKPOINT: 100
  THRESHOLDS:
    TRAIN: 0.0
    VALIDATION: 0.0

MODEL:
  TYPE: 'unet'
  IN_CHANNELS: 12

DATALOADER:
  MODE: 'fusion'
  FUSION_DROPOUT: True