_BASE_: "base.yaml"
DEBUG: False
SAVE_CHECKPOINTS: [10, 15, 20, 25, 30]
INFERENCE:
  CHECKPOINT: 15
  THRESHOLDS:
    TRAIN: 0.00
    VALIDATION: 0.00

MODEL:
  TYPE: 'dualstreamunet'
  IN_CHANNELS: 12

TRAINER:
  EPOCHS: 30
  BATCH_SIZE: 8

DATALOADER:
  MODE: 'fusion'

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.1
  WEIGHT_DECAY: 0.998
  APPLY_THRESHOLD: False
  CONSISTENCY_LOSS_TYPE: 'JaccardLikeLoss'

AUGMENTATION:
  COLOR_SHIFT: False
  GAMMA_CORRECTION: True