_BASE_: "base.yaml"
DEBUG: False
INFERENCE:
  CHECKPOINT: 0
  THRESHOLDS:
    TRAIN: 0.00
    VALIDATION: 0.00

MODEL:
  TYPE: 'dualstreamunet'
  IN_CHANNELS: 12

DATALOADER:
  MODE: 'fusion'

AUGMENTATION:
  GAMMA_CORRECTION: False
