_BASE_: "base.yaml"
DEBUG: False
LOG_FREQ: 500
SAVE_CHECKPOINTS: [5, 10, 15, 20]
INFERENCE:
  CHECKPOINT: 20
  THRESHOLDS:
    TRAIN: 0.49
    VALIDATION: 0.48

MODEL:
  TYPE: 'dualstreamunet'
  IN_CHANNELS: 12

TRAINER:
  EPOCHS: 20

DATALOADER:
  MODE: 'fusion'
  INCLUDE_UNLABELED: True

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.1
  WEIGHT_DECAY: 0.998
  APPLY_THRESHOLD: False
  CONSISTENCY_LOSS_TYPE: 'JaccardLikeLoss'