_BASE_: "base.yaml"
DEBUG: False
INFERENCE:
  CHECKPOINT: 20
  THRESHOLDS:
    TRAIN: 0.00
    VALIDATION: 0.00

MODEL:
  TYPE: 'unet'
  IN_CHANNELS: 12

DATALOADER:
  MODE: 'fusion'

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 1
  WEIGHT_DECAY: 0.998
  APPLY_THRESHOLD: False
  CONSISTENCY_LOSS_TYPE: 'MeanSquareErrorLoss'