_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    NUM_CLASSES: 1
SOLVER:
  STEPS: (210000, 250000)
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025
  MAX_ITER: 200000
