_BASE_: "optical.yaml"
DEBUG: False
INFERENCE:
  CHECKPOINT: 50
  THRESHOLDS:
    TRAIN: 0.0
    VALIDATION: 0.0

MODEL:
  TYPE: 'unet'
  IN_CHANNELS: 10


DATALOADER:
  MODE: 'optical'

TRAINER:
  BATCH_SIZE: 8

CONSISTENCY_TRAINER:
  APPLY_THRESHOLD: True
  LOSS_FACTOR: 0.1