_BASE_: "base.yaml"
DEBUG: False
INFERENCE:
  CHECKPOINT: 0
  THRESHOLDS:
    TRAIN: 0.0
    VALIDATION: 0.0

MODEL:
  TYPE: 'unet'
  IN_CHANNELS: 10

TRAINER:
  LR: 1e-4

DATALOADER:
  MODE: 'optical'