_BASE_: "optical.yaml"
DEBUG: True
THRESHOLDS:
  TRAIN: 0.0
  VALIDATION: 0.0

MODEL:
  TYPE: 'unet'
  IN_CHANNELS: 10

DATASETS:
  TRAINING: ['denver']
  UNLABELED: ['stockholm']

DATALOADER:
  MODE: 'optical'

TRAINER:
  BATCH_SIZE: 8