_BASE_: "base.yaml"
THRESH: 0.0

MODEL:
  IN_CHANNELS: 6
  BACKBONE:
    ENABLED: True
    TYPE: 'resnet34'
    PRETRAINED_WEIGHTS: 'imagenet'

TRAINER:
  LR: 1e-3

DATALOADER:
  SENTINEL1_BANDS: []
  SENTINEL2_BANDS: ['B4', 'B3', 'B2', 'B8', 'B11', 'B12']