_BASE_: "base.yaml"
DATASETS:
  TRAIN: ("/local_storage/datasets/xview2/small/train/",)
  TEST: ("/storage/yonk/xview2_dataset/test/",)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 2
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025
  STEPS: (60000, 80000)
  MAX_ITER: 400000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
