_BASE_: "base_version4.yaml"
DEBUG: False
THRESHOLDS:
  TRAIN: 0.43
  VALIDATION: 0.37

MODEL:
  IN_CHANNELS: 2

DATALOADER:
  MODE: 'sar'
  SENTINEL1_BANDS: ['VV', 'VH']

DATASETS:
  SITES:
    TRAINING: ['denver', 'saltlakecity', 'phoenix', 'lasvegas', 'toronto', 'columbus', 'winnipeg', 'dallas',
               'minneapolis', 'miami', 'montreal', 'quebec', 'albuquerque', 'losangeles', 'kansascity',
               'charlston', 'seattle', 'daressalam', 'elpaso', 'sandiego', 'santafe', 'stgeorge', 'tucson']
    VALIDATION: ['sanfrancisco', 'atlanta', 'vancouver', 'calgary', 'kampala']