_BASE_: "base.yaml"
DEBUG: False
INFERENCE:
  CHECKPOINT: 50
  THRESHOLDS:
    TRAIN: 0.0
    VALIDATION: 0.0

MODEL:
  IN_CHANNELS: 4

DATALOADER:
  MODE: 'sar'
  SENTINEL1_BANDS: ['VV_mean', 'VV_stdDev', 'VH_mean', 'VH_stdDev']