_BASE_: "base_v2.yaml"
DEBUG: False
THRESH: 0.0

MODEL:
  TYPE: 'unet'
  IN_CHANNELS: 2

DATALOADER:
  MODE: 'sar'
  SENTINEL1_BANDS: ['VV', 'VH']
  SENTINEL2_BANDS: []

DATASETS:
  SITES:
    TRAINING: ['denver', 'saltlakecity', 'phoenix', 'lasvegas', 'toronto', 'columbus', 'winnipeg', 'dallas',
               'minneapolis', 'atlanta', 'miami', 'montreal', 'quebec', 'albuquerque', 'losangeles', 'kansascity',
               'charlston', 'seattle']
    VALIDATION: ['houston', 'sanfrancisco', 'vancouver', 'newyork', 'calgary']