_BASE_: "base.yaml"
DEBUG: False
INFERENCE:
  CHECKPOINT: 0
  THRESHOLDS:
    TRAIN: 0.00
    VALIDATION: 0.00

MODEL:
  TYPE: 'simpleconfidencenet'
  IN_CHANNELS: 2
  LOSS_TYPE: 'MeanSquareErrorLoss'

DATALOADER:
  MODE: 'sar'