_BASE_: "base_v3.yaml"
DEBUG: False
THRESHOLDS:
  TRAIN: 0.36
  VALIDATION: 0.34

MODEL:
  TOPOLOGY: [64, 128,]
  IN_CHANNELS: 11

DATALOADER:
  MODE: 'optical'
  SENTINEL2_BANDS: ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B11', 'B12']
  AUXILIARY_INPUTS: ['prediction_sar_gamma_smallnet']

AUGMENTATION:
  COLOR_SHIFT: False
  GAMMA_CORRECTION: True