_BASE_: "unet_dice2x.yaml"
OUTPUT_BASE_DIR: ('/local_storage/users/pshi/logs/unet/')
AUGMENTATION:
  # Random cropping of the images
  CROP_TYPE: 'uniform'
  CROP_SIZE: 256
  IMAGE_OVERSAMPLING_TYPE: 'simple'
